service: skwash

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: af-south-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: production
    runtime: provided.al2
    lambdaHashingVersion: 20201221

    environment:
        APP_NAME: Skwash
        APP_KEY: ${ssm:/skwash/app-key}
        APP_ENV: production
        APP_URL: https://skwash.bergh.tech
        APP_DEBUG: true
        XDG_CONFIG_HOME: /tmp
        DB_CONNECTION: mysql
        DB_PORT: 3306
        DB_HOST: ${ssm:/trials/db-host}
        DB_DATABASE: ${ssm:/skwash/db-database}
        DB_USERNAME: ${ssm:/trials/db-username}
        DB_PASSWORD: ${ssm:/trials/db-password}
        RELEASE_HASH: ${env:RELEASE_HASH}
        ASSET_URL: !Join [ '', [ 'https://', !GetAtt AssetsBucket.RegionalDomainName ] ]
        MIX_ASSET_URL: !Join [ '', [ 'https://', !GetAtt AssetsBucket.RegionalDomainName ] ]
        MAIL_MAILER: ses

    iam:
        role:
            managedPolicies:
                - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
                - "arn:aws:iam::aws:policy/AmazonSESFullAccess"

package:
    # Directories to exclude from deployment
    exclude:
        - .env
        - node_modules/**
        - public/storage/**
        - public/css/**
        - public/js/**
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        memorySize: 1024
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        memorySize: 1024
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref

resources:
  Resources:
    # Website assets
    AssetsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: skwash-prod-assets
            # AccelerateConfiguration:
            #   AccelerationStatus: Enabled
            CorsConfiguration:
                CorsRules:
                    -   AllowedHeaders: [ "*" ]
                        AllowedMethods: [ GET ]
                        AllowedOrigins: [ "*" ]

    # Policy to make website assets publicly readable
    AssetsBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref AssetsBucket
            PolicyDocument:
                Statement:
                    -   Effect: Allow
                        Principal: '*' # everyone
                        Action: 's3:GetObject' # to read
                        Resource: 'arn:aws:s3:::skwash-prod-assets/*'
