name: Deploy

# Deploy master on push
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.todo'

permissions:
  contents: read
  id-token: write

env:
  OIDC_ROLE: arn:aws:iam::779498940176:role/berghtech-OIDC-GHActions-role
  DEPLOYMENT_REGION: af-south-1
  DEPLOYMENT_STAGE: production
  DEPLOYMENT_NAME: skwash
  PHP_VERSION: '8.1'
  PHP_EXTENSIONS: 'curl, dom, bcmath, mbstring, zip'

jobs:

  deploy-assets:
    name: Deploy assets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs"

      - name: Laravel Mix
        run: npm run prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          role-session-name: ${{ env.DEPLOYMENT_NAME }}-assets-deployer
          aws-region: ${{ env.DEPLOYMENT_REGION }}

      - name: Upload assets to s3
        run: aws s3 sync ./public s3://${{ env.DEPLOYMENT_NAME }}-prod-assets --delete --exclude 'index.php' --exclude '.htaccess' --exclude 'robots.txt' --exclude 'web.config'

  deploy-serverless:
    name: Deploy Serverless stack
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - name: Laravel Mix
        run: npm run prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          role-session-name: ${{ env.DEPLOYMENT_NAME }}-code-deployer
          aws-region: ${{ env.DEPLOYMENT_REGION }}

      - name: Serverless Deploy
        run: ./node_modules/.bin/sls deploy
        env:
          RELEASE_HASH: ${{ github.sha }}

  migrate-db:
    name: Run database migrations
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ deploy-serverless ]
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          role-session-name: ${{ env.DEPLOYMENT_NAME }}-migrations-deployer
          aws-region: ${{ env.DEPLOYMENT_REGION }}

      - name: Run database migration
        run: ./node_modules/.bin/sls bref:cli "migrate --force --ansi --no-interaction"
